name: For production by push and update cms

on:
  push:
    branches:
      - main
  issue_comment:
    types: [created, edited]
  workflow_dispatch:

jobs:
  #for Push
  build:
    name: Build(pushed)
    if: (github.repository == 'kdi0618/vlog-site' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
        env:
          NEXT_PUBLIC_GTM_ID: ${{ secrets.NEXT_PUBLIC_GTM_ID }}
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}-${{ github.run_id }}
          path: dist
          retention-days: 7
      - name: Webhook
        uses: diverta/workflow-webhook@v2
        env:
          webhook_url: "https://share-with.g.kuroco.app/direct/menu/github/"
          webhook_secret: "0fc0a26aea284bf17920c0846bf3e459"
          data: '{"single_zip":"0","domain":"share-with.g.kuroco-front.app", "repository":"${{ github.repository }}", "run_id":"${{ github.run_id }}", "hash":"${{ github.sha }}"}'

  deploy:
    # Specify the job order
    needs: build

    runs-on: ubuntu-latest

    steps:
    # Get built results
    - name: Download build result
      uses: actions/download-artifact@v3
      with:
        name: ${{ github.sha }}-${{ github.run_id }}
        path: dist/
    # Upload to S3
    - name: Publish to AWS S3
      uses: opspresso/action-s3-sync@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        FROM_PATH: "dist/"
        DEST_PATH: ${{ secrets.S3_URI }}
    # Clear the cache of cloudfront
    - name: Clear cache in CloudFront
      uses: chetan/invalidate-cloudfront-action@v1.2
      env:
        DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
        PATHS: "/*"
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
