name: CI/CD

# trigger
on:
  push:
    branches: [ main ]
  repository_dispatch:
    branches: [ main ]
    types: [update_post]

# Run build and deploy jobs in sequence
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.18.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn build
    # Upload build results to give it to deploy job
    - name: Upload build result
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: dist/

  deploy:
    # Specify the job order
    needs: build

    runs-on: ubuntu-latest

    steps:
    # Get built results
    - name: Download build result
      uses: actions/download-artifact@v2
      with:
        name: build
        path: dist/
    # Upload to S3
    - name: Publish to AWS S3
      uses: opspresso/action-s3-sync@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        FROM_PATH: "dist/"
        DEST_PATH: ${{ secrets.S3_URI }}
    # Clear the cache of cloudfront
    - name: Clear cache in CloudFront
      uses: chetan/invalidate-cloudfront-action@v1.2
      env:
        DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
        PATHS: "/*"
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
